---

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=development # TODO change for prod
    command: npm run dev # TODO change for prod
    user: "node"

