---

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # - .:/usr/app # Useful for hot reloading, remove for prod
      - /usr/app/node_modules  # Avoid overwriting node_modules with host's (especially on Linux)
    environment:
      - NODE_ENV=development # TODO change for prod
    working_dir: /usr/app
    command: npm run dev # TODO change for prod
    user: "node"

