name: j42l-app

services:
    db:
        image: postgres:17.5-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - app-data:/var/lib/postgresql/data
        networks:
            - app-network

    app:
        build: .
        environment:
            - WEBAPP_URL=${WEB_APP_URL}
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
            - BETTER_AUTH_URL=${WEB_APP_URL}
            - BETTER_AUTH_CLIENT_ID=${BETTER_AUTH_CLIENT_ID}
            - BETTER_AUTH_CLIENT_SECRET=${BETTER_AUTH_CLIENT_SECRET}
        networks:
            - app-network

volumes:
    app-data:

networks:
    app-network:
