services:
    db:
        ports:
            - 5432:5432
    app:
        ports:
            - 80:3000
        volumes:
            - ./src:/usr/app/src
            - ./migrations:/usr/app/migrations
