import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased">
				<div className="max-w-3xl mx-auto">
					<header>
						<a href="#">Projects</a>
						<a href="#">Applications</a>
					</header>
					{children}
				</div>
			</body>
		</html>
	);
}
